name: Deploy Production

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
          logLevel:
            description: 'Log level'
            required: true
            default: 'warning'
          tags:
            description: 'Test scenario tags'
            required: false


jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        # - name: Checkout code
        #   uses: actions/checkout@v4

        # - name: Copy files to EC2
        #   uses: appleboy/scp-action@v0.1.7
        #   with:
        #     host: ${{ secrets.EC2_HOST }}
        #     username: ${{ secrets.EC2_USER }}
        #     key: ${{ secrets.EC2_SSH_KEY }}
        #     source: "."
        #     target: "~/chainlink-app"

        # run commands as done manually via ssh

        - name: Run deployment commands on EC2
          uses: appleboy/ssh-action@v0.1.10
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              cd /var/www/html/chainlink/connexx-chainlink
              git pull
              cd ChainLink-Client
              sudo npx vite build
              pm2 restart "ChainLink Server"