name: ESLint Check
on:
  push:
    branches:
      - main
      - cicd-pipeline
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      - name: Install Dependencies (Client)
        if: hashFiles('ChainLink-Client/package-lock.json') != ''
        run: cd ChainLink-Client && npm ci

      - name: Run ESLint (Client)
        run: cd ChainLink-Client && npm run lint

      - name: Run Prettier Check
        working-directory: ChainLink-Client
        run: npx prettier --check .