name: Run Tests

on:
  push:
    branches:
      - main
      - cicd-pipeline
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install and run tests for Server
        run: cd ChainLink-Server && npm install && npm test

      - name: Install and run tests for Client
        run: cd ChainLink-Client && npm install && npm test