name: Run Tests

on:
  push:
    branches:
      - main
      - cicd-pipeline
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (Server)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
        working-directory: ChainLink-Server

      - name: Install Dependencies (Server)
        run: npm install
        working-directory: ChainLink-Server

      - name: Run Server Tests
        run: npm test
        working-directory: ChainLink-Server

      - name: Setup Node.js (Client)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
        working-directory: ChainLink-Client

      - name: Install Dependencies (Client)
        run: npm install
        working-directory: ChainLink-Client

      - name: Run Client Tests
        run: npm test
        working-directory: ChainLink-Client