name: Run Tests

on:
  push:
    branches:
      - main
      - cicd-pipeline
  pull_request:
    branches:
      - main

jobs:
  server-test:
    name: Server Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ChainLink-Server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Dependencies (Server)
        run: npm install

      - name: Run Server Tests
        run: npm test

  client-test:
    name: Client Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ChainLink-Client
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Dependencies (Client)
        run: npm install

      - name: Run Client Tests
        run: npm test