name: Run Tests

on:
  push:
    branches:
      - main
      - cicd-pipeline
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "echo 'MongoDB is healthy'" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install and run tests for Server
        run: cd ChainLink-Server && npm install && npm test

      - name: Install and run tests for Client
        run: cd ChainLink-Client && npm install && npm test